# Generated by Django 4.2.7 on 2023-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shrotenedurl",
            name="short_url",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
